grails-app/domain/com/odobo/eschool/Absence.groovy
package com.odobo.eschool

class Absence {

    Date date
    Boolean justifiableCause = false

    static belongsTo = [course:Course, student:Student]

    static constraints = {
        date(nullable: false)
    }
}

grails-app/domain/com/odobo/eschool/StudentGroup.groovy
package com.odobo.eschool

class StudentGroup {

    String name

    static belongsTo = [course:Course]

    static hasMany = [students:Student]

    static constraints = {
        name(blank:false)
    }

    String toString(){
        "${name} ${course}"
    }

    def getTeachers(){
        def teachers = []
        StudentGroupTeacher.findAllByStudentGroup(this).each { sgt ->
            teachers.add(sgt.teacher)
        }

        teachers
    }

    def searchStudents(String name, String surnames){
        this.students.findAll { it.name.toLowerCase() == name.toLowerCase() || it.surnames.toLowerCase() == surnames.toLowerCase() }
    }
}

grails-app/controllers/com/odobo/eschool/AbsenceController.groovy
package com.odobo.eschool

import org.springframework.dao.DataIntegrityViolationException

class AbsenceController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def create(Long id) {
        [absenceInstance: new Absence(params), studentGroupInstance:StudentGroup.get(id)]
    }

    def save() {
        def absenceInstance = new Absence(params)
        if (!absenceInstance.save(flush: true)) {
            render(view: "create", model: [absenceInstance: absenceInstance, studentGroupInstance:StudentGroup.get(params.studentGroupInstance.id)])
            return
        }

        flash.message = message(code: 'default.created.message', args: [message(code: 'absence.label', default: 'Absence'), absenceInstance.id])
        redirect(action: "show", id: absenceInstance.id, params: [studentGroupInstanceId:params.studentGroupInstance.id])
    }

    def show(Long id) {
        def absenceInstance = Absence.get(id)
        if (!absenceInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'absence.label', default: 'Absence'), id])
            redirect(action: "list")
            return
        }

        [absenceInstance: absenceInstance, studentGroupInstance: StudentGroup.get(params.studentGroupInstanceId)]
    }

    def delete(Long id) {
        def absenceInstance = Absence.get(id)
        if (!absenceInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'absence.label', default: 'Absence'), id])
            redirect(action: "showAbsencesByStudentAndStudentGroup", id: params.studentGroupId)
            return
        }

        try {
            absenceInstance.delete(flush: true)
            render(template: "listAbsences", model: [studentGroupInstance:StudentGroup.get(params.studentGroupId)])
        }
        catch (DataIntegrityViolationException e) {
            flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'absence.label', default: 'Absence'), id])
            redirect(action: "showAbsencesByStudentAndStudentGroup", id: id, params: [studentGroupId:params.studentGroupId])
        }
    }

    def showAbsencesByStudentAndStudentGroup(Long id) {
        [studentGroupInstance:StudentGroup.get(id)]
    }

    def changeJustifiable(Long id) {
        def absenceInstance  = Absence.get(id)
        absenceInstance.justifiableCause = absenceInstance.justifiableCause ? false : true
        absenceInstance.save(flush:true)

        render(template: "listAbsences", model: [studentGroupInstance:StudentGroup.get(params.studentGroupId)])
    }

    def search(){
        def studentGroupInstance = StudentGroup.get(params.studentGroupInstance.id)
        def studentInstanceList = studentGroupInstance.searchStudents(params.searchName, params.searchSurnames)

        render(template:"searchAbsences", model:[studentInstanceList: studentInstanceList, studentGroupInstance:studentGroupInstance])
    }
}

grails-app/views/absence/_form.gsp
<%@ page import="com.odobo.eschool.Absence" %>



<div class="fieldcontain ${hasErrors(bean: absenceInstance, field: 'date', 'error')} required">
	<label for="date">
		<g:message code="absence.date.label" default="Date" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="date" precision="day"  value="${absenceInstance?.date}"  />
</div>

<div class="fieldcontain ${hasErrors(bean: absenceInstance, field: 'justifiableCause', 'error')} ">
	<label for="justifiableCause">
		<g:message code="absence.justifiableCause.label" default="Justifiable Cause" />
		
	</label>
	<g:checkBox name="justifiableCause" value="${absenceInstance?.justifiableCause}" />
</div>

<div class="fieldcontain ${hasErrors(bean: absenceInstance, field: 'student', 'error')} required">
	<label for="student">
		<g:message code="absence.student.label" default="Student" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="student" name="student.id" from="${com.odobo.eschool.StudentGroup.get(studentGroupInstance.id).students}" optionKey="id" required="" value="${absenceInstance?.student?.id}" class="many-to-one"/>
</div>
<g:hiddenField name="studentGroupInstance.id" value="${studentGroupInstance.id}"/>
<g:hiddenField name="course.id" value="${studentGroupInstance.course.id}"/>

grails-app/views/absence/_listAbsences.gsp
<%@ page import="com.odobo.eschool.Absence" %>

<g:each in="${studentGroupInstance.students}" var="studentInstance">
    <h1>${studentInstance}</h1>
    <table>
        <thead>
        <tr>

            <th>${message(code: 'absence.date.label', default: 'Date')}</th>

            <th>${message(code: 'absence.justifiableCause.label', default: 'Justifiable Cause')}</th>

            <th>Actions</th>

        </tr>
        </thead>
        <tbody>
        <g:each in="${studentInstance.getAbsencesByCourse(studentGroupInstance.course)}" status="i" var="absenceInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:formatDate date="${absenceInstance.date}" format="MM/dd/yyyy"/></td>

                <td>${absenceInstance.justifiableCause ? 'Yes': 'No'}</td>

                <td>
                    <g:remoteLink action="changeJustifiable"
                                  id="${absenceInstance.id}"
                                  update="absenceList"
                                  params="[studentGroupId:studentGroupInstance.id]">${absenceInstance.justifiableCause ? 'Mark as unjustifiable' : 'Mark as justifiable' }</g:remoteLink>
                    | <g:remoteLink action="delete"
                                    id="${absenceInstance.id}"
                                    update="absenceList"
                                    params="[studentGroupId:studentGroupInstance.id]">Delete</g:remoteLink>
                </td>

            </tr>
        </g:each>
        </tbody>
    </table>
</g:each>

grails-app/views/absence/_searchAbsences.gsp
<%@ page import="com.odobo.eschool.Absence" %>

<g:each in="${studentInstanceList}" var="studentInstance">
    <h1>${studentInstance}</h1>
    <table>
        <thead>
        <tr>

            <th>${message(code: 'absence.date.label', default: 'Date')}</th>

            <th>${message(code: 'absence.justifiableCause.label', default: 'Justifiable Cause')}</th>

            <th>Actions</th>

        </tr>
        </thead>
        <tbody>
        <g:each in="${studentInstance.getAbsencesByCourse(studentGroupInstance.course)}" status="i" var="absenceInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:formatDate date="${absenceInstance.date}" format="MM/dd/yyyy"/></td>

                <td>${absenceInstance.justifiableCause ? 'Yes': 'No'}</td>

                <td>
                    <g:remoteLink action="changeJustifiable"
                                  id="${absenceInstance.id}"
                                  update="absenceList"
                                  params="[studentGroupId:studentGroupInstance.id]">${absenceInstance.justifiableCause ? 'Mark as unjustifiable' : 'Mark as justifiable' }</g:remoteLink>
                    | <g:remoteLink action="delete"
                                    id="${absenceInstance.id}"
                                    update="absenceList"
                                    params="[studentGroupId:studentGroupInstance.id]">Delete</g:remoteLink>
                </td>

            </tr>
        </g:each>
        </tbody>
    </table>
</g:each>

grails-app/views/absence/create.gsp
<%@ page import="com.odobo.eschool.Absence" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'absence.label', default: 'Absence')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-absence" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="showAbsencesByStudentAndStudentGroup" id="${studentGroupInstance.id}"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-absence" class="content scaffold-create" role="main">
			<h1><g:message code="default.createAbsence.label" default="Create absence for {0}" args="[studentGroupInstance]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${absenceInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${absenceInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form action="save" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/absence/list.gsp
<%@ page import="com.odobo.eschool.Absence" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'absence.label', default: 'Absence')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-absence" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-absence" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<g:sortableColumn property="date" title="${message(code: 'absence.date.label', default: 'Date')}" />
					
						<th><g:message code="absence.course.label" default="Course" /></th>
					
						<g:sortableColumn property="justifiableCause" title="${message(code: 'absence.justifiableCause.label', default: 'Justifiable Cause')}" />
					
						<th><g:message code="absence.student.label" default="Student" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${absenceInstanceList}" status="i" var="absenceInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${absenceInstance.id}">${fieldValue(bean: absenceInstance, field: "date")}</g:link></td>
					
						<td>${fieldValue(bean: absenceInstance, field: "course")}</td>
					
						<td><g:formatBoolean boolean="${absenceInstance.justifiableCause}" /></td>
					
						<td>${fieldValue(bean: absenceInstance, field: "student")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${absenceInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/absence/show.gsp
<%@ page import="com.odobo.eschool.Absence" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'absence.label', default: 'Absence')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-absence" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="showAbsencesByStudentAndStudentGroup" id="${studentGroupInstance.id}"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
		</div>
		<div id="show-absence" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list absence">
			
				<g:if test="${absenceInstance?.date}">
				<li class="fieldcontain">
					<span id="date-label" class="property-label"><g:message code="absence.date.label" default="Date" /></span>
					
						<span class="property-value" aria-labelledby="date-label"><g:formatDate date="${absenceInstance?.date}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${absenceInstance?.course}">
				<li class="fieldcontain">
					<span id="course-label" class="property-label"><g:message code="absence.course.label" default="Course" /></span>
					
						<span class="property-value" aria-labelledby="course-label">${absenceInstance?.course?.encodeAsHTML()}</span>
					
				</li>
				</g:if>
			
				<li class="fieldcontain">
					<span id="justifiableCause-label" class="property-label"><g:message code="absence.justifiableCause.label" default="Justifiable Cause" /></span>
					
						<span class="property-value" aria-labelledby="justifiableCause-label"><g:formatBoolean boolean="${absenceInstance?.justifiableCause}" /></span>
					
				</li>

				<g:if test="${absenceInstance?.student}">
				<li class="fieldcontain">
					<span id="student-label" class="property-label"><g:message code="absence.student.label" default="Student" /></span>
					
						<span class="property-value" aria-labelledby="student-label">${absenceInstance?.student?.encodeAsHTML()}</span>
					
				</li>
				</g:if>
			
			</ol>
		</div>
	</body>
</html>

grails-app/views/absence/showAbsencesByStudentAndStudentGroup.gsp
<%@ page import="com.odobo.eschool.Absence" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'absence.label', default: 'Absence')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-absence" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create" id="${studentGroupInstance.id}"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-absence" class="content scaffold-list" role="main">
			<h1><g:message code="default.listAbsencesByCourse.label" args="[studentGroupInstance]" default="List absences in {0}" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
            <div style="padding-left:26px;">
                <g:formRemote name="search" url="[controller:'absence', action:'search']" update="absenceList">
                    <label for="searchName">Search</label>
                    <g:textField id="searchName" name="searchName"/>
                    <g:textField id="searchSurnames" name="searchSurnames"/>
                    <g:hiddenField name="studentGroupInstance.id" value="${studentGroupInstance.id}"/>
                    <g:submitButton name="searchButton" value="Search"/>
                </g:formRemote>
            </div>
            <div id="absenceList">
                <g:each in="${studentGroupInstance.students}" var="studentInstance">
                    <h1>${studentInstance}</h1>
                    <table>
                        <thead>
                            <tr>

                                <th>${message(code: 'absence.date.label', default: 'Date')}</th>

                                <th>${message(code: 'absence.justifiableCause.label', default: 'Justifiable Cause')}</th>

                                <th>Actions</th>

                            </tr>
                        </thead>
                        <tbody>
                        <g:each in="${studentInstance.getAbsencesByCourse(studentGroupInstance.course)}" status="i" var="absenceInstance">
                            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                                <td><g:formatDate date="${absenceInstance.date}" format="MM/dd/yyyy"/></td>

                                <td>${absenceInstance.justifiableCause ? 'Yes': 'No'}</td>

                                <td>
                                    <g:remoteLink action="changeJustifiable"
                                                  id="${absenceInstance.id}"
                                                  update="absenceList"
                                                  params="[studentGroupId:studentGroupInstance.id]">${absenceInstance.justifiableCause ? 'Mark as unjustifiable' : 'Mark as justifiable' }</g:remoteLink>
                                    | <g:remoteLink action="delete"
                                                    id="${absenceInstance.id}"
                                                    update="absenceList"
                                                    params="[studentGroupId:studentGroupInstance.id]">Delete</g:remoteLink>

                                </td>

                            </tr>
                        </g:each>
                        </tbody>
                    </table>
                </g:each>
            </div>
		</div>
	</body>
</html>